/** Course wrap-up glossary — part 1 (technical & course activities). */
export const WRAP_UP_GLOSSARY_PART1: { term: string; definition: string }[] = [
  { term: "UTXO (Unspent Transaction Output)", definition: "A discrete output of a Bitcoin transaction that has not yet been spent." },
  { term: "Mempool", definition: "Collection of unconfirmed transactions waiting to be included in a block." },
  { term: "Block Header", definition: "Metadata of a block, including previous block hash, Merkle root, timestamp, difficulty, version, and nonce." },
  { term: "Merkle Root", definition: "Single hash representing all transactions in a block for verification." },
  { term: "Nonce", definition: "Number miners adjust to solve the Proof-of-Work puzzle." },
  { term: "Fee Rate", definition: "Amount of Bitcoin paid per byte or virtual byte for transaction processing." },
  { term: "Subsidy / Block Reward", definition: "Incentive for miners, including newly minted Bitcoin and transaction fees." },
  { term: "SegWit (Segregated Witness)", definition: "Protocol upgrade separating signature data from transaction data for efficiency." },
  { term: "PSBT (Partially Signed Bitcoin Transaction)", definition: "Standardized format for collaborative or multi-step signing of transactions." },
  { term: "Multi-Sig (M-of-N)", definition: "Wallet setup requiring M of N signatures to authorize spending." },
  { term: "Hardware Signer / Hardware Wallet", definition: "An offline device used to store private keys and sign transactions securely." },
  { term: "Change Address", definition: "A wallet-generated address used to receive any leftover Bitcoin from a transaction." },
  { term: "Coin Control", definition: "User-directed selection of specific UTXOs for spending." },
  { term: "Timelock (CLTV / CSV)", definition: "A script condition that restricts spending until a specific time or block height is reached." },
  { term: "Lightning Network (LN)", definition: "Layer 2 solution for fast, low-fee payments using payment channels." },
  { term: "Sidechains", definition: "Blockchains pegged to Bitcoin, enabling experimentation or faster settlements." },
  { term: "Circular Economies", definition: "Markets operating entirely on Bitcoin or satoshis." },
  { term: "Difficulty Adjustment", definition: "Recalibration of mining difficulty every 2,016 blocks to maintain ~10-minute block times." },
  { term: "Security Budget", definition: "Total incentives (subsidy + fees) securing the Bitcoin network." },
  { term: "ASIC (Application-Specific Integrated Circuit)", definition: "Mining hardware optimized for Bitcoin computations." },
  { term: "Full Node", definition: "A Bitcoin client that independently validates blocks and transactions, ensuring the integrity of the blockchain." },
  { term: "Channel Open / Close", definition: "Locking and releasing funds in a Lightning Network channel." },
  { term: "Watchtower", definition: "Service monitoring Lightning channels to prevent fraud or cheating." },
  { term: "P2PKH (Pay-to-PubKey-Hash)", definition: "Standard Bitcoin script type for single-sig addresses." },
  { term: "P2WPKH (Pay-to-Witness-PubKey-Hash)", definition: "SegWit version of P2PKH for efficiency and malleability resistance." },
  { term: "P2SH (Pay-to-Script-Hash)", definition: "Allows complex spending conditions hidden until the UTXO is spent." },
  { term: "P2TR (Pay-to-Taproot)", definition: "A Taproot transaction type that allows for private and flexible spending conditions." },
  { term: "Locking Script (scriptPubKey)", definition: "Defines conditions required to spend a UTXO." },
  { term: "Unlocking Script (scriptSig / witness)", definition: "The script data that satisfies the locking script." },
  { term: "Trust-Minimized Finance", definition: "Systems relying on protocol rules instead of intermediaries." },
  { term: "Coordinator / Coordinator-Less Flow", definition: "Methods for managing multi-sig transaction coordination." },
  { term: "Fee Window", definition: "Optimal time for submitting transactions to reduce fees." },
  { term: "Noisy UTXO Set", definition: "A wallet with many small, fragmented outputs that affect privacy and fees." },
  { term: "Coin Join", definition: "Privacy technique combining multiple users’ transactions to obscure ownership." },
  { term: "Block Explorer", definition: "A tool to view blockchain transactions, blocks, confirmations, and fees." },
  { term: "Proof-of-Work (PoW)", definition: "A mining algorithm that requires computational effort to validate blocks." },
  { term: "Halving Schedule", definition: "Reduction of block subsidy approximately every four years." },
  { term: "Monetary Supply Limit (21 million BTC)", definition: "The maximum number of bitcoins that will ever exist." },
  { term: "Raw Transaction / Serialization", definition: "Hexadecimal representation of a transaction’s data structure." },
  { term: "Genesis Block", definition: "The first block in the Bitcoin blockchain." },
  { term: "Chain Linking / Immutability", definition: "Blocks reference previous blocks, making the chain tamper-evident." },
  { term: "Wallet Types", definition: "Hot wallet (online), cold wallet (offline)." },
  { term: "Seed Phrase / Passphrase", definition: "Mnemonic phrase for wallet recovery and backup." },
  { term: "UTXO Labeling / Transaction Labeling", definition: "Tracking funds for future spending and privacy management." },
  { term: "Explorer Scavenger Hunt", definition: "Activity to verify transactions, confirmations, and Merkle proofs." },
  { term: "Dry-Run Recovery", definition: "Testing wallet recovery without real funds." },
  { term: "Consolidation Plan", definition: "Strategy for combining small UTXOs to optimize fees and privacy." },
  { term: "Multi-Sig Custody Plan", definition: "Designing collaborative wallets for families or organizations." },
  { term: "Lightning Payment Demo", definition: "Practical exercise demonstrating Layer 2 payments." },
  { term: "Proof-of-Work by Hand", definition: "A classroom simulation demonstrating mining and difficulty." },
  { term: "Simulated Channel Open/Close", definition: "Lightning channel exercise on testnet or regtest." },
  { term: "Good Bitcoin Hygiene", definition: "Practices like using new addresses per receive, labeling, and avoiding reuse." },
  { term: "Hardware Signer Operations", definition: "Setup, backup, signing, and recovery testing with hardware wallets." },
  { term: "Layer 2 Concepts", definition: "Lightning channels, routing, sidechains, and settlement trade-offs." },
  { term: "Node Operations", definition: "Full node syncing, policy enforcement, mempool monitoring, and verification." },
  { term: "Mining Concepts", definition: "Pools, centralization risk, ASIC supply chains, geopolitical risk, subsidy vs fee balance." },
  { term: "Timelock & Script Policies", definition: "CLTV, CSV, vaults, inheritance, and delayed spending setups." },
  { term: "Bitcoin Philosophy Terms", definition: "Chartalist money, metallist money, platform money, Bitcoin vs bitcoin, trust in code vs state." },
  { term: "Financial Sovereignty Concepts", definition: "Inflation-resistant micro-savings, censorship resistance, trust-minimized finance." },
  { term: "Money", definition: "Medium of exchange, store of value, and unit of account." },
  { term: "Functions of Money", definition: "Medium of exchange, store of value, unit of account." },
  { term: "Properties of Sound Money", definition: "Scarce, durable, portable, divisible, and recognizable." },
  { term: "Barter System", definition: "The direct exchange of goods or services without the use of money." },
  { term: "Commodity Money", definition: "Money with intrinsic value, such as gold or silver." },
  { term: "Fiat Money", definition: "Government-issued currency not backed by a physical commodity." },
  { term: "Monetary Inflation", definition: "An increase in the money supply reduces purchasing power." },
  { term: "CPI Inflation", definition: "Changes in the consumer price index reflecting price-level changes." },
  { term: "Financial Exclusion", definition: "Lack of access to banking or financial services." },
  { term: "Cypherpunks", definition: "Advocates for cryptography, privacy, and decentralized currencies." },
  { term: "Satoshi Nakamoto", definition: "Pseudonymous creator of Bitcoin." },
  { term: "Bitcoin Whitepaper", definition: "A 2008 document describing Bitcoin as peer-to-peer electronic cash." },
  { term: "Digital Signatures", definition: "Cryptographic proofs verifying ownership and authorization." },
  { term: "Public Key", definition: "Cryptographic key used to receive Bitcoin." },
  { term: "Private Key", definition: "Secret key used to sign transactions." },
  { term: "Software Wallet", definition: "Application managing private keys and transactions on desktop or mobile." },
  { term: "First Transaction (Send/Receive)", definition: "Initial Bitcoin transfer experience." },
  { term: "Privacy Basics", definition: "Practices like using VPNs, avoiding address reuse, and local-first tools." },
  { term: "Role-play Bitcoin Transaction", definition: "Classroom activity simulating sending, verifying, and mining Bitcoin." },
  { term: "Build a Paper Blockchain", definition: "A physical demonstration of block linking and immutability." },
  { term: "Address Reuse", definition: "Using the same Bitcoin address multiple times, which can compromise privacy and security." },
];
