/** Course wrap-up glossary — part 2 (extended reference). */
export const WRAP_UP_GLOSSARY_PART2: { term: string; definition: string }[] = [
  { term: "Ancient Coins", definition: "Historical examples of commodity money." },
  { term: "ASIC Resistance", definition: "Designing mining algorithms to prevent dominance by ASICs." },
  { term: "Atomic Swap", definition: "Trustless exchange of cryptocurrencies across different blockchains." },
  { term: "BIP (Bitcoin Improvement Proposal)", definition: "Standardized proposal for protocol changes." },
  { term: "BIP125 (RBF - Replace-By-Fee)", definition: "A mechanism that allows unconfirmed transactions to be replaced by higher-fee versions." },
  { term: "Block Subsidy Halving", definition: "Event reducing new Bitcoin issuance per block by 50%." },
  { term: "Broadcast", definition: "Sending a transaction to the Bitcoin network for confirmation." },
  { term: "Canonical Transaction Ordering (CTOR)", definition: "Rule for ordering transactions in a block." },
  { term: "Chain Tip", definition: "The most recent block in the longest blockchain." },
  { term: "Child-Pays-for-Parent (CPFP)", definition: "Fee strategy where a new transaction incentivizes mining of a low-fee parent transaction." },
  { term: "Clearing vs Settlement", definition: "Difference between recording transactions and finalizing ownership." },
  { term: "Coin Maturity", definition: "The number of confirmations required before a coin can be spent." },
  { term: "Coinbase Transaction", definition: "The first transaction in a block that awards the miner." },
  { term: "Cold Storage", definition: "Offline storage of private keys for security." },
  { term: "Commitment Transaction", definition: "In Lightning, a transaction that represents channel state." },
  { term: "Confidential Transactions", definition: "A technique for hiding amounts in a blockchain transaction." },
  { term: "Covenants", definition: "Script conditions restricting how coins can be spent in the future." },
  { term: "CPFP Fee Bump", definition: "Using a child transaction to raise the effective fee of an unconfirmed transaction." },
  { term: "Cryptographic Hash Function", definition: "A function that maps data to a fixed-length string, used for integrity verification." },
  { term: "Custodial Wallet", definition: "A wallet where a third party controls the private keys." },
  { term: "Decentralization", definition: "Distribution of control away from a single authority." },
  { term: "Derivation Path", definition: "Sequence used to generate hierarchical deterministic (HD) wallet keys." },
  { term: "Difficulty Target", definition: "The value a block hash must meet for valid mining." },
  { term: "Dust Output", definition: "Tiny UTXO with value too small to spend economically." },
  { term: "Dynamic Fee Estimation", definition: "Wallet feature predicting optimal fees based on mempool and network congestion." },
  { term: "Electrum (wallet)", definition: "A lightweight Bitcoin wallet that connects to servers instead of running a full node." },
  { term: "Encrypted Backup", definition: "Backup of wallet data secured with a password or passphrase." },
  { term: "Escrow Transaction", definition: "Funds held temporarily by a trusted party until conditions are met." },
  { term: "Exit Node", definition: "Lightning or sidechain node used to settle funds back to the main chain." },
  { term: "Extended Public Key (xPub)", definition: "Master key used to generate public addresses without exposing private keys." },
  { term: "Extended Private Key (xPrv)", definition: "Master key used to derive all private keys in an HD wallet." },
  { term: "Federated Sidechain", definition: "Sidechain controlled by a group of trusted entities." },
  { term: "Fee Market", definition: "A system where transaction priority is determined by fees offered." },
  { term: "Finality", definition: "The point at which a transaction is considered irreversible." },
  { term: "First-Mover Advantage", definition: "Early adoption benefits in Bitcoin networks." },
  { term: "Fork", definition: "Split in the blockchain due to different rules or consensus." },
  { term: "Fungibility", definition: "The property of each unit of currency being interchangeable with any other unit of the same currency." },
  { term: "Full Block", definition: "Block containing the maximum number of transactions allowed." },
  { term: "Genesis Hash", definition: "Hash of the genesis block, used as blockchain anchor." },
  { term: "Hash Rate", definition: "Computational power applied to mining." },
  { term: "Hardened Derivation", definition: "Key derivation that prevents certain attacks in HD wallets." },
  { term: "Hot Wallet", definition: "A wallet connected to the internet, used for spending." },
  { term: "Human-Readable Timestamp", definition: "Representation of block time in a readable format." },
  { term: "Immutable Ledger", definition: "A record that cannot be changed once confirmed." },
  { term: "Inclusion Proof", definition: "Proof that a transaction exists in a block (Merkle proof)." },
  { term: "Input & Output", definition: "Transaction components specifying sources and destinations of funds." },
  { term: "Ledger State", definition: "Current record of all balances and UTXOs." },
  { term: "Lightning Invoice", definition: "Payment request in Lightning Network specifying amount, expiry, and routing info." },
  { term: "Liquidity Provider", definition: "Participant making funds available for trading or payment routing." },
  { term: "Locktime (Absolute/Relative)", definition: "A restriction that prevents transaction spending until a specific block height or time." },
  { term: "Local-First Tools", definition: "Software prioritizing local data storage over remote servers." },
  { term: "Malicious Miner", definition: "Miner attempting double-spends or censorship." },
  { term: "Merkle Path", definition: "A sequence of hashes used to verify a transaction within a block." },
  { term: "Micro-Savings", definition: "Small, incremental Bitcoin savings strategies." },
  { term: "Mnemonic Phrase", definition: "A sequence of words representing a wallet seed for backup." },
  { term: "Mixing Service", definition: "Third-party service combining coins to enhance privacy." },
  { term: "Non-Custodial Wallet", definition: "A wallet where the user controls private keys." },
  { term: "Nonce Reuse", definition: "Using the same nonce in cryptographic operations is a security risk." },
  { term: "Off-Chain Transactions", definition: "Payments or transfers conducted outside the main blockchain." },
  { term: "On-Chain Transaction", definition: "Transaction recorded on the Bitcoin blockchain." },
  { term: "OP_CHECKMULTISIG", definition: "Script operation enabling multi-signature validation." },
  { term: "OP_RETURN", definition: "Script opcode used to embed data in a transaction." },
  { term: "Opt-in RBF", definition: "Wallet feature allowing transaction replacement with a higher fee." },
  { term: "Output Script", definition: "Conditions specifying how a UTXO can be spent." },
  { term: "Payment Channel", definition: "Two-party off-chain ledger for fast, repeated payments." },
  { term: "Peer-to-Peer Network", definition: "A network where nodes communicate directly without intermediaries." },
  { term: "Policy Rule", definition: "Node-specific rule affecting transaction acceptance or relaying." },
  { term: "Private Key Backup", definition: "A secure copy of the private key for recovery." },
  { term: "Protocol Upgrade", definition: "Change to Bitcoin rules via consensus or soft/hard forks." },
  { term: "Public Key Hash", definition: "Hashed version of a public key used in standard addresses." },
  { term: "Raw Block Data", definition: "Full block content including transactions, scripts, and metadata." },
  { term: "Relay Policy", definition: "Rules determining which transactions or blocks a node forwards." },
  { term: "Replace-By-Fee (RBF)", definition: "A mechanism that allows low-fee transactions to be replaced with higher-fee ones." },
  { term: "Satoshi", definition: "Smallest divisible unit of Bitcoin (0.00000001 BTC)." },
  { term: "Satoshi Nakamoto Vision", definition: "Original principles and philosophy guiding Bitcoin’s design." },
  { term: "ScriptPubKey", definition: "Script locking a UTXO." },
  { term: "ScriptSig", definition: "Script unlocking a UTXO." },
  { term: "Seed Backup Testing", definition: "Verifying wallet recovery using the seed phrase." },
  { term: "Security Model", definition: "Design ensuring funds are protected against attacks." },
  { term: "Segregated Witness Address", definition: "Address type leveraging SegWit for efficiency." },
  { term: "Session Timing (Trading / Lightning)", definition: "Activity schedules and best-practice windows." },
  { term: "Signed Transaction", definition: "Transaction verified with a private key signature." },
  { term: "Single-Signature Wallet", definition: "A wallet that requires only one signature to spend funds." },
  { term: "Smart Contract (Bitcoin Context)", definition: "Script executing predefined conditions automatically." },
  { term: "Soft Fork", definition: "Backward-compatible protocol upgrade." },
  { term: "Spend Plan", definition: "Strategy for when and how to spend UTXOs." },
  { term: "SPV (Simplified Payment Verification)", definition: "A lightweight verification method for transactions without a full node." },
  { term: "Stale Block", definition: "Valid block that is not included in the main chain." },
  { term: "Sovereign Bitcoin User", definition: "An individual controlling private keys and funds independently." },
  { term: "Testnet", definition: "A Bitcoin network used for testing without real value." },
  { term: "Transaction Fee", definition: "Payment to miners for including transactions in blocks." },
  { term: "Transaction ID (TXID)", definition: "Unique hash identifying a transaction." },
  { term: "Transaction Lifecycle", definition: "Process from creation, signing, broadcasting, confirmation, to spending." },
  { term: "Trustless", definition: "A system where verification does not rely on trusted intermediaries." },
  { term: "Vault", definition: "Setup with delayed spending or additional security measures." },
  { term: "Verify Inclusion", definition: "Confirming a transaction exists in a block via Merkle path." },
  { term: "Watchtower Monitoring", definition: "Observing channels to detect and prevent fraudulent closure." },
  { term: "Weighted Blocks / vBytes", definition: "Measure of block size accounting for witness data." },
  { term: "Whitepaper Exercise", definition: "Classroom activity studying Bitcoin whitepaper excerpt." },
  { term: "Zero-Confirmation Transaction", definition: "Transaction broadcast but not yet included in a block." },
];
